### ISSUE TITLE
Different exit codes

### ISSUE THREAD

**Issue by wwwfyl** [falk-werner/zipsign#10]
It would be great to get a detailed answer instead of FAIL about the reasons.
I would like different exit codes for:
- checksum error
- certificate error

**Comment by falk-werner** [comment]
Thanks for your interest. I'm not sure whether I understand correctly: Which are the cases you want do distinguish?

- the zip is not signed
- the zip is signed, but the verification fails

or the reason why the verification fails:
- the provided certificate chain is invalid
- the signature is incorrect

**Comment by wwwfyl** [comment]
Hello! and thank you for your reply!
I mean the following reasons:
- The supplied certificate chain is invalid
- The signature is incorrect

For example, for these situations:
- the archive was corrupted on delivery, but it was signed with the correct certificates.
- the archive was not corrupted, but was signed with different certificates

**Comment by falk-werner** [comment]
Sounds great. I will do this.

**Comment by wwwfyl** [comment]
Thanks a lot!
