### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by MrWildanMD** [falk-werner/zipsign#24]
**Is your feature request related to a problem? Please describe.**
Yep, when developing in local which is mac os based, it can't be executed due to difference between OpenSSL and LibreSSL maybe? but it worked well in linux server

**Describe the solution you'd like**
Mac OS build support

**Describe alternatives you've considered**
-

**Additional context**
I tried to build from source it throws error like openssl/err.h doesn't exists or blahblah...that's why i'm opening this, thanks in advance

**Comment by MrWildanMD** [comment]
```
WMD0502@PID-ITSEC-WMD0502 zipsign-1.3.0 % ls
CMakeLists.txt	README.md	cmake		docker		lib		test
LICENSE		build		codecov.yml	include		src
WMD0502@PID-ITSEC-WMD0502 zipsign-1.3.0 % cd build
WMD0502@PID-ITSEC-WMD0502 build % make
[  4%] Built target base64
[ 16%] Built target cli
[ 18%] Building CXX object CMakeFiles/openssl++.dir/lib/openssl++/exception.cc.o
/Users/WMD0502/repo/zipsign-1.3.0/lib/openssl++/exception.cc:7:10: fatal error: 'openssl/err.h' file not found
#include <openssl/err.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/openssl++.dir/lib/openssl++/exception.cc.o] Error 1
make[1]: *** [CMakeFiles/openssl++.dir/all] Error 2
make: *** [all] Error 2
WMD0502@PID-ITSEC-WMD0502 build % openssl version
LibreSSL 3.3.6
```
this when i try to build from source/release

**Comment by falk-werner** [comment]
Hallo @MrWildanMD,

thanks for the request. I like your suggestion to add Mac OS support.
I've never worked with Mac OS before, so I might need some time to dig into it. Please stay tuned.

**Comment by falk-werner** [comment]
@MrWildanMD, please take a look at [PR25](https://github.com/falk-werner/zipsign/pull/25).
It seemed, that I messed up with some include paths and library paths of OpenSSL in `CMakeLists.txt`. Thanks a lot for discovering the bug.

I want to add unit test execution to the branch before it is reintegrated. After that, a new version will be released.

**Comment by MrWildanMD** [comment]
Alright, thanks for your response, i appreciate that

**Comment by falk-werner** [comment]
[v1.4.0](https://github.com/falk-werner/zipsign/releases/tag/v1.4.0) is released including Mac OS support.
