### ISSUE TITLE
how to update or renew certificates

### ISSUE THREAD

**Issue by wwwfyl** [falk-werner/zipsign#26]
Some time ago, I generated a key pair as the manual said to do. 

The certificate is about to expire, and I would like advice on how to issue a new certificate so that it will allow verification of previously signed archives and new ones.

**Comment by falk-werner** [comment]
Hello @wwwfyl ,

I suppose you followed the instructions in the `tl;dr` section. If so, you have created a self signed certificate and used it to sign your archives. You can follow the same steps to create a new certificate and key and the same way and sign new archives with the new certificate. To verify the archive, you can just specify multiple `-c` options on the command line:

```bash
zipsign verify -f archive.zip -c old_cert.pem -c new_cert.pem
```

A more sophisticated solution is to use a more complex PKI: create a root certificate (and key) with a long duration (e.g. 10 years). The root certificate is used to issue signing certificates with a rather short duration (e.g.. a year). When signing use the `-e` option to embed the signing certificate in archive. To verify the archive, use the root certificate.  
While this is not a solution for your current situation, it might help to update certificates in the future.

Note that zipsign also supports to sign an archive using multiple signers by repeating the `-p` and `-c` arguments in the sign command. However the current implementation will check the validity of all signatures in that case.

**Comment by wwwfyl** [comment]
Thanks for the detailed answer to my question!
